// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('f:/Workspace/CT/Point/client/node_modules/react');
var { Component } = React;
var ReactNative = require('f:/Workspace/CT/Point/client/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('Point', appParameters);
});
require('f:/Workspace/CT/Point/client/index.js');